name: tubes_app
description: A new Flutter application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.7
  shared_preferences: ^2.1.0
  timezone: ^0.9.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^10.0.0
  sqflite: ^2.2.0
  path: ^1.8.0
  


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  
